services:
  db:
    image: postgres:17.0
    container_name: postgres-db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PGUSER}       
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    healthcheck:                     
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: huanyezz/demoapp:1.0
    ports:
      - 5000:5005
    volumes:
      - shared-files:/files
    environment:
      - APP_ENV=${APP_ENV}
      - DB_USER=${PGUSER}
      - DB_PORT=5432
      - DB_PASSWORD=${PGPASSWORD}
      - DB_NAME=${PGDATABASE}
      - DB_HOST=db  
    depends_on:
      db:
        condition: service_healthy  

volumes:
  shared-files:
    driver: local
  postgres-data:
    driver: local